# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis\folders_instalation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 274)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_input_videos_folder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_input_videos_folder.setGeometry(QtCore.QRect(20, 70, 581, 31))
        self.text_input_videos_folder.setObjectName("text_input_videos_folder")
        self.text_input_playlist_folder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_input_playlist_folder.setGeometry(QtCore.QRect(20, 130, 581, 31))
        self.text_input_playlist_folder.setObjectName("text_input_playlist_folder")
        self.text_input_whatsapp_folder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_input_whatsapp_folder.setGeometry(QtCore.QRect(20, 190, 581, 31))
        self.text_input_whatsapp_folder.setObjectName("text_input_whatsapp_folder")
        self.label_video_folders = QtWidgets.QLabel(self.centralwidget)
        self.label_video_folders.setGeometry(QtCore.QRect(30, 50, 49, 16))
        self.label_video_folders.setObjectName("label_video_folders")
        self.label_playlist_folders = QtWidgets.QLabel(self.centralwidget)
        self.label_playlist_folders.setGeometry(QtCore.QRect(30, 110, 131, 16))
        self.label_playlist_folders.setObjectName("label_playlist_folders")
        self.label_whatsapp_folders = QtWidgets.QLabel(self.centralwidget)
        self.label_whatsapp_folders.setGeometry(QtCore.QRect(30, 170, 121, 16))
        self.label_whatsapp_folders.setObjectName("label_whatsapp_folders")
        self.title_label_folders = QtWidgets.QLabel(self.centralwidget)
        self.title_label_folders.setGeometry(QtCore.QRect(20, 20, 581, 16))
        self.title_label_folders.setObjectName("title_label_folders")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_input_videos_folder.setPlainText(_translate("MainWindow", "path_to_videos"))
        self.text_input_playlist_folder.setPlainText(_translate("MainWindow", "path_to_playlists"))
        self.text_input_whatsapp_folder.setPlainText(_translate("MainWindow", "path_to_contacts"))
        self.label_video_folders.setText(_translate("MainWindow", "Videos:"))
        self.label_playlist_folders.setText(_translate("MainWindow", "Videos from Playlists:"))
        self.label_whatsapp_folders.setText(_translate("MainWindow", "Folder dow WhatsApp:"))
        self.title_label_folders.setText(_translate("MainWindow", "Please confirm the path to the folders where the videos and information will be saved:"))

if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())