# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
import sys
import os

try: os.chdir(os.path.dirname(__file__))
except Exception as err:
    input(err)


import json
import git

from PyQt5 import QtCore, QtGui, QtWidgets

# import Modules

files_of_objectivism = os.listdir()

class Ui_MainWindow(object):
    def check_for_updates():
    
        repo_url = 'https://github.com/user/repo.git'
        repo_dir = 'repo'
        settings_file = 'settings.json'

        with open(f'{repo_dir}/{settings_file}', 'r') as f:
            settings = json.load(f)

        if settings['settings']['version'] != 'your_variable':
            repo = git.Repo(repo_dir)
            remote = repo.remote()
            remote.fetch()
            repo.git.reset('--hard', 'origin/master')

    
    def avvia_download(self):
        import Functions.Download as app
    
    def avvia_playlist(self):
        import Functions.Playlist as app
    
    def avvia_whatsapp(self):
        import Functions.WhatsApp as app
    
    def avvia_analytics(self):
        import Functions.Analytics as app
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.progressBar_app = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_app.setGeometry(QtCore.QRect(170, 10, 140, 23))
        self.progressBar_app.setProperty("value", 0)
        self.progressBar_app.setObjectName("progressBar_app")
        
        self.pushButton_update_app = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update_app.setGeometry(QtCore.QRect(20, 10, 140, 24))
        self.pushButton_update_app.setObjectName("pushButton_update_app")
        
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setGeometry(QtCore.QRect(20, 60, 140, 51))
        self.pushButton_download.setObjectName("pushButton_download")
        
        self.pushButton_playlist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_playlist.setGeometry(QtCore.QRect(20, 120, 140, 51))
        self.pushButton_playlist.setObjectName("pushButton_playlist")
        
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(170, 60, 140, 51))
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        
        # Connect WhatsApp:
        self.pushButton_whatsapp.clicked.connect(self.avvia_whatsapp)

        
        self.pushButton_analytics = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_analytics.setGeometry(QtCore.QRect(170, 120, 140, 51))
        self.pushButton_analytics.setObjectName("pushButton_analytics")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Push Buttons
        self.pushButton_analytics
        self.pushButton_download
        self.pushButton_update_app
        self.pushButton_whatsapp
        self.pushButton_playlist
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_update_app.setText(_translate("MainWindow", "Check for Updates"))
        self.pushButton_download.setText(_translate("MainWindow", "Download/Edit Videos"))
        self.pushButton_playlist.setText(_translate("MainWindow", "Download Playlists"))
        self.pushButton_whatsapp.setText(_translate("MainWindow", "WhatsApp App"))
        self.pushButton_analytics.setText(_translate("MainWindow", "Analytics"))
        
if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())
